# Starship configuration

# Inserts a blank line between shell prompts
add_newline = true

# Set the format of the prompt
format = """$os$username$directory$git_branch$git_status$nodejs$golang$julia$python$ruby$character"""

# Right Prompt Configuration
right_format = """$cmd_duration$shell$battery$time"""

[os]
format = "[$symbol]($style) "
style = "fg:#26C6DA"
disabled = false

[os.symbols]
Windows = "î˜ª"
Ubuntu = "îœ’"
SUSE = "SUSE"
Raspbian = "ïŒ•"
Mint = "ïŒ"
Macos = "îœ‘"
Manjaro = "ïŒ’"
Linux = "ïŒš"
Gentoo = "ïŒ"
Fedora = "ïŒŠ"
Debian = "î½"
CentOS = "ïŒ„"
Arch = "ïŒƒ"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "ï…»"

[username]
style_user = "fg:#1951c9"
style_root = "fg:#ffff66"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
style = "fg:#20b664"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
symbol = "î‚ "
style = "fg:#fffb38"
format = "[$symbol $branch]($style) "

[git_status]
style = "fg:#fffb38"
format = '([$all_status$ahead_behind]($style)) '
conflicted = "=${count}"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?${count}"
stashed = "ï£–${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "âœ˜${count}"

[character]
success_symbol = "[ó°„¾](bold green)"
error_symbol = "[ó°„¾](bold red)"
vicmd_symbol = "[â®](bold green)"

[nodejs]
format = "[îœ˜ $version](fg:#6CA35E) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[golang]
format = "[î˜§ $version](fg:#8ED1F7) "

[julia]
format = "[î˜¤ $version](fg:#4063D8) "

[python]
format = "[î˜† $version](fg:#FFDE57) "
pyenv_version_name = true

[ruby]
format = "[îœ¹ $version](fg:#AE1401) "

#[aws]
#symbol = "î˜"
#format = '[$symbol ($profile@$region)]($style) '
#style = "fg:#FFA400"
#
#[azure]
#disabled = false
#format = "[ï´ƒ $subscription]($style) "
#style = "blue"

[cmd_duration]
min_time = 1000
format = "[$duration]($style) "
style = "fg:#83769c"
show_milliseconds = true

[shell]
format = "[$indicator]($style) "
zsh_indicator = "zsh"
powershell_indicator = "pwsh"
bash_indicator = "bash"
disabled = false
style = "fg:#0077c2"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"

[time]
disabled = false
format = "at [$time]($style) "
style = "fg:#2e9599"
use_12hr = false
show_milliseconds = true

#[gcloud]
#format = "on [î² $project]($style) "
#style = "fg:#d83cbe"
#
#[kubernetes]
#format = 'on [ï´± $context(::$namespace)]($style) '
#style = "fg:#d83cbe"
#disabled = false
